# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\SATRUST\Desktop\WorkMate 3.0 Pro\designs\xml\vault_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vault_tab(object):
    def setupUi(self, Vault_tab):
        Vault_tab.setObjectName("Vault_tab")
        Vault_tab.resize(524, 382)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Vault_tab.sizePolicy().hasHeightForWidth())
        Vault_tab.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Vault_tab)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tbl_vault = QtWidgets.QTableWidget(Vault_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_vault.sizePolicy().hasHeightForWidth())
        self.tbl_vault.setSizePolicy(sizePolicy)
        self.tbl_vault.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.tbl_vault.setRowCount(4)
        self.tbl_vault.setObjectName("tbl_vault")
        self.tbl_vault.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_vault.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_vault.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_vault.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tbl_vault.setHorizontalHeaderItem(3, item)
        self.tbl_vault.horizontalHeader().setVisible(True)
        self.tbl_vault.horizontalHeader().setCascadingSectionResizes(False)
        self.tbl_vault.verticalHeader().setHighlightSections(True)
        self.verticalLayout.addWidget(self.tbl_vault)

        self.retranslateUi(Vault_tab)
        QtCore.QMetaObject.connectSlotsByName(Vault_tab)

    def retranslateUi(self, Vault_tab):
        _translate = QtCore.QCoreApplication.translate
        Vault_tab.setWindowTitle(_translate("Vault_tab", "Form"))
        item = self.tbl_vault.horizontalHeaderItem(0)
        item.setText(_translate("Vault_tab", "Name"))
        item = self.tbl_vault.horizontalHeaderItem(1)
        item.setText(_translate("Vault_tab", "URL"))
        item = self.tbl_vault.horizontalHeaderItem(2)
        item.setText(_translate("Vault_tab", "Username"))
        item = self.tbl_vault.horizontalHeaderItem(3)
        item.setText(_translate("Vault_tab", "Password"))
