# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/browser_import_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BrowserPasswordImportWindow(object):
    def setupUi(self, BrowserPasswordImportWindow):
        BrowserPasswordImportWindow.setObjectName("BrowserPasswordImportWindow")
        BrowserPasswordImportWindow.resize(1044, 363)
        BrowserPasswordImportWindow.setAcceptDrops(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(BrowserPasswordImportWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_name = QtWidgets.QLabel(BrowserPasswordImportWindow)
        self.lbl_name.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout.addWidget(self.lbl_name)
        self.lbl_username = QtWidgets.QLabel(BrowserPasswordImportWindow)
        self.lbl_username.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_username.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_username.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_username.setObjectName("lbl_username")
        self.horizontalLayout.addWidget(self.lbl_username)
        self.lbl_url = QtWidgets.QLabel(BrowserPasswordImportWindow)
        self.lbl_url.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_url.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_url.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_url.setObjectName("lbl_url")
        self.horizontalLayout.addWidget(self.lbl_url)
        self.lbl_password = QtWidgets.QLabel(BrowserPasswordImportWindow)
        self.lbl_password.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_password.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_password.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_password.setObjectName("lbl_password")
        self.horizontalLayout.addWidget(self.lbl_password)
        self.lbl_import = QtWidgets.QLabel(BrowserPasswordImportWindow)
        self.lbl_import.setMinimumSize(QtCore.QSize(200, 0))
        self.lbl_import.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lbl_import.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_import.setObjectName("lbl_import")
        self.horizontalLayout.addWidget(self.lbl_import)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.frame = QtWidgets.QFrame(BrowserPasswordImportWindow)
        self.frame.setStyleSheet("background-color: #9ecd16;")
        self.frame.setFrameShape(QtWidgets.QFrame.HLine)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.vbox_items = QtWidgets.QVBoxLayout()
        self.vbox_items.setObjectName("vbox_items")
        self.verticalLayout.addLayout(self.vbox_items)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_import = QtWidgets.QPushButton(BrowserPasswordImportWindow)
        self.btn_import.setObjectName("btn_import")
        self.horizontalLayout_2.addWidget(self.btn_import)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(BrowserPasswordImportWindow)
        QtCore.QMetaObject.connectSlotsByName(BrowserPasswordImportWindow)

    def retranslateUi(self, BrowserPasswordImportWindow):
        _translate = QtCore.QCoreApplication.translate
        BrowserPasswordImportWindow.setWindowTitle(_translate("BrowserPasswordImportWindow", "Import Passwords From Browser"))
        self.lbl_name.setText(_translate("BrowserPasswordImportWindow", "Name"))
        self.lbl_username.setText(_translate("BrowserPasswordImportWindow", "UserName"))
        self.lbl_url.setText(_translate("BrowserPasswordImportWindow", "URL"))
        self.lbl_password.setText(_translate("BrowserPasswordImportWindow", "Password"))
        self.lbl_import.setText(_translate("BrowserPasswordImportWindow", "Import"))
        self.btn_import.setText(_translate("BrowserPasswordImportWindow", "Import"))
