# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/existing_user_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExistingUser(object):
    def setupUi(self, ExistingUser):
        ExistingUser.setObjectName("ExistingUser")
        ExistingUser.resize(664, 205)
        self.verticalLayout = QtWidgets.QVBoxLayout(ExistingUser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_database = QtWidgets.QLabel(ExistingUser)
        self.lbl_database.setObjectName("lbl_database")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_database)
        self.lbl_key_file = QtWidgets.QLabel(ExistingUser)
        self.lbl_key_file.setObjectName("lbl_key_file")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_key_file)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lne_database = QtWidgets.QLineEdit(ExistingUser)
        self.lne_database.setObjectName("lne_database")
        self.horizontalLayout.addWidget(self.lne_database)
        self.tbtn_database = QtWidgets.QToolButton(ExistingUser)
        self.tbtn_database.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbtn_database.setText("")
        self.tbtn_database.setObjectName("tbtn_database")
        self.horizontalLayout.addWidget(self.tbtn_database)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lne_key_file = QtWidgets.QLineEdit(ExistingUser)
        self.lne_key_file.setObjectName("lne_key_file")
        self.horizontalLayout_2.addWidget(self.lne_key_file)
        self.tbtn_key_file = QtWidgets.QToolButton(ExistingUser)
        self.tbtn_key_file.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tbtn_key_file.setText("")
        self.tbtn_key_file.setObjectName("tbtn_key_file")
        self.horizontalLayout_2.addWidget(self.tbtn_key_file)
        self.formLayout.setLayout(1, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.formLayout)
        self.lbl_keys = QtWidgets.QLabel(ExistingUser)
        self.lbl_keys.setMinimumSize(QtCore.QSize(0, 30))
        self.lbl_keys.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_keys.setObjectName("lbl_keys")
        self.verticalLayout.addWidget(self.lbl_keys)
        self.gbox_keys = QtWidgets.QGridLayout()
        self.gbox_keys.setObjectName("gbox_keys")
        self.verticalLayout.addLayout(self.gbox_keys)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_create = QtWidgets.QPushButton(ExistingUser)
        self.btn_create.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_create.setObjectName("btn_create")
        self.horizontalLayout_3.addWidget(self.btn_create)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(ExistingUser)
        QtCore.QMetaObject.connectSlotsByName(ExistingUser)

    def retranslateUi(self, ExistingUser):
        _translate = QtCore.QCoreApplication.translate
        ExistingUser.setWindowTitle(_translate("ExistingUser", "Form"))
        self.lbl_database.setText(_translate("ExistingUser", "Database"))
        self.lbl_key_file.setText(_translate("ExistingUser", "Key File"))
        self.lbl_keys.setText(_translate("ExistingUser", "Keys"))
        self.btn_create.setText(_translate("ExistingUser", "Create"))
