# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(413, 241)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_loader = QtWidgets.QLabel(Dialog)
        self.lbl_loader.setMinimumSize(QtCore.QSize(0, 200))
        self.lbl_loader.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_loader.setObjectName("lbl_loader")
        self.verticalLayout.addWidget(self.lbl_loader)
        self.lbl_backup_message = QtWidgets.QLabel(Dialog)
        self.lbl_backup_message.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_backup_message.setObjectName("lbl_backup_message")
        self.verticalLayout.addWidget(self.lbl_backup_message)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Loading Please Wait"))
        self.lbl_loader.setText(_translate("Dialog", "Loading Image"))
        self.lbl_backup_message.setText(_translate("Dialog", "Backing Up To Remote Storage..."))
