# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadingDialog(object):
    def setupUi(self, LoadingDialog):
        LoadingDialog.setObjectName("LoadingDialog")
        LoadingDialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoadingDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_loading_message = QtWidgets.QLabel(LoadingDialog)
        self.lbl_loading_message.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_loading_message.setObjectName("lbl_loading_message")
        self.verticalLayout.addWidget(self.lbl_loading_message)

        self.retranslateUi(LoadingDialog)
        QtCore.QMetaObject.connectSlotsByName(LoadingDialog)

    def retranslateUi(self, LoadingDialog):
        _translate = QtCore.QCoreApplication.translate
        LoadingDialog.setWindowTitle(_translate("LoadingDialog", "Loading..."))
        self.lbl_loading_message.setText(_translate("LoadingDialog", "Loading..."))
