# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoaderWidget(object):
    def setupUi(self, LoaderWidget):
        LoaderWidget.setObjectName("LoaderWidget")
        LoaderWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(LoaderWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_image = QtWidgets.QLabel(LoaderWidget)
        self.lbl_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_image.setObjectName("lbl_image")
        self.verticalLayout.addWidget(self.lbl_image)
        self.lbl_backup_message = QtWidgets.QLabel(LoaderWidget)
        self.lbl_backup_message.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_backup_message.setObjectName("lbl_backup_message")
        self.verticalLayout.addWidget(self.lbl_backup_message)

        self.retranslateUi(LoaderWidget)
        QtCore.QMetaObject.connectSlotsByName(LoaderWidget)

    def retranslateUi(self, LoaderWidget):
        _translate = QtCore.QCoreApplication.translate
        LoaderWidget.setWindowTitle(_translate("LoaderWidget", "Please Wait"))
        self.lbl_image.setText(_translate("LoaderWidget", "Loading Image"))
        self.lbl_backup_message.setText(_translate("LoaderWidget", "Backing Up To Remote Storage. Please Wait..."))
