# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Note_Window(object):
    def setupUi(self, Note_Window):
        Note_Window.setObjectName("Note_Window")
        Note_Window.resize(641, 494)
        self.verticalLayout = QtWidgets.QVBoxLayout(Note_Window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.notes_window_hbox = QtWidgets.QHBoxLayout()
        self.notes_window_hbox.setObjectName("notes_window_hbox")
        self.chkbx_edit = QtWidgets.QCheckBox(Note_Window)
        self.chkbx_edit.setObjectName("chkbx_edit")
        self.notes_window_hbox.addWidget(self.chkbx_edit)
        self.btn_save = QtWidgets.QPushButton(Note_Window)
        self.btn_save.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_save.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_save.setObjectName("btn_save")
        self.notes_window_hbox.addWidget(self.btn_save)
        self.btn_copy_note = QtWidgets.QPushButton(Note_Window)
        self.btn_copy_note.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_copy_note.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_copy_note.setObjectName("btn_copy_note")
        self.notes_window_hbox.addWidget(self.btn_copy_note)
        self.btn_delete_note = QtWidgets.QPushButton(Note_Window)
        self.btn_delete_note.setMinimumSize(QtCore.QSize(150, 0))
        self.btn_delete_note.setMaximumSize(QtCore.QSize(150, 16777215))
        self.btn_delete_note.setObjectName("btn_delete_note")
        self.notes_window_hbox.addWidget(self.btn_delete_note)
        self.verticalLayout.addLayout(self.notes_window_hbox)
        self.lnedt_title = QtWidgets.QLineEdit(Note_Window)
        self.lnedt_title.setObjectName("lnedt_title")
        self.verticalLayout.addWidget(self.lnedt_title)
        self.txtedt_body = QtWidgets.QTextEdit(Note_Window)
        self.txtedt_body.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.txtedt_body.setObjectName("txtedt_body")
        self.verticalLayout.addWidget(self.txtedt_body)

        self.retranslateUi(Note_Window)
        QtCore.QMetaObject.connectSlotsByName(Note_Window)

    def retranslateUi(self, Note_Window):
        _translate = QtCore.QCoreApplication.translate
        Note_Window.setWindowTitle(_translate("Note_Window", "Note"))
        self.chkbx_edit.setText(_translate("Note_Window", "Editable"))
        self.btn_save.setText(_translate("Note_Window", "Save"))
        self.btn_copy_note.setText(_translate("Note_Window", "Copy"))
        self.btn_delete_note.setText(_translate("Note_Window", "Delete"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Note_Window = QtWidgets.QWidget()
    ui = Ui_Note_Window()
    ui.setupUi(Note_Window)
    Note_Window.show()
    sys.exit(app.exec_())
