# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Register(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(461, 199)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.form_register = QtWidgets.QFormLayout()
        self.form_register.setObjectName("form_register")
        self.lbl_name = QtWidgets.QLabel(Dialog)
        self.lbl_name.setObjectName("lbl_name")
        self.form_register.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_name)
        self.lbl_password = QtWidgets.QLabel(Dialog)
        self.lbl_password.setObjectName("lbl_password")
        self.form_register.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_password)
        self.lbl_question = QtWidgets.QLabel(Dialog)
        self.lbl_question.setObjectName("lbl_question")
        self.form_register.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_question)
        self.lbl_answer = QtWidgets.QLabel(Dialog)
        self.lbl_answer.setObjectName("lbl_answer")
        self.form_register.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_answer)
        self.lbl_password2 = QtWidgets.QLabel(Dialog)
        self.lbl_password2.setObjectName("lbl_password2")
        self.form_register.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_password2)
        self.lbl_email = QtWidgets.QLabel(Dialog)
        self.lbl_email.setObjectName("lbl_email")
        self.form_register.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_email)
        self.lnedt_name = QtWidgets.QLineEdit(Dialog)
        self.lnedt_name.setObjectName("lnedt_name")
        self.form_register.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lnedt_name)
        self.lnedt_email = QtWidgets.QLineEdit(Dialog)
        self.lnedt_email.setObjectName("lnedt_email")
        self.form_register.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lnedt_email)
        self.lnedt_password = QtWidgets.QLineEdit(Dialog)
        self.lnedt_password.setObjectName("lnedt_password")
        self.form_register.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lnedt_password)
        self.lnedt_password2 = QtWidgets.QLineEdit(Dialog)
        self.lnedt_password2.setObjectName("lnedt_password2")
        self.form_register.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lnedt_password2)
        self.lnedt_question = QtWidgets.QLineEdit(Dialog)
        self.lnedt_question.setObjectName("lnedt_question")
        self.form_register.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lnedt_question)
        self.lnedt_answer = QtWidgets.QLineEdit(Dialog)
        self.lnedt_answer.setObjectName("lnedt_answer")
        self.form_register.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lnedt_answer)
        self.verticalLayout.addLayout(self.form_register)
        self.btn_register = QtWidgets.QPushButton(Dialog)
        self.btn_register.setObjectName("btn_register")
        self.verticalLayout.addWidget(self.btn_register)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Register"))
        self.lbl_name.setText(_translate("Dialog", "Name"))
        self.lbl_password.setText(_translate("Dialog", "Password"))
        self.lbl_question.setText(_translate("Dialog", "Security Question"))
        self.lbl_answer.setText(_translate("Dialog", "Answer"))
        self.lbl_password2.setText(_translate("Dialog", "Confirm Password"))
        self.lbl_email.setText(_translate("Dialog", "Email"))
        self.btn_register.setText(_translate("Dialog", "Register"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
