# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/reset_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResetPassword(object):
    def setupUi(self, ResetPassword):
        ResetPassword.setObjectName("ResetPassword")
        ResetPassword.resize(400, 182)
        self.verticalLayout = QtWidgets.QVBoxLayout(ResetPassword)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_message = QtWidgets.QLabel(ResetPassword)
        self.lbl_message.setObjectName("lbl_message")
        self.verticalLayout.addWidget(self.lbl_message)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapAllRows)
        self.formLayout.setObjectName("formLayout")
        self.lbl_password1 = QtWidgets.QLabel(ResetPassword)
        self.lbl_password1.setObjectName("lbl_password1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_password1)
        self.lbl_confirm_password = QtWidgets.QLabel(ResetPassword)
        self.lbl_confirm_password.setObjectName("lbl_confirm_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_confirm_password)
        self.lnedt_password1 = QtWidgets.QLineEdit(ResetPassword)
        self.lnedt_password1.setObjectName("lnedt_password1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lnedt_password1)
        self.lnedit_confirm_password = QtWidgets.QLineEdit(ResetPassword)
        self.lnedit_confirm_password.setObjectName("lnedit_confirm_password")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lnedit_confirm_password)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_reset = QtWidgets.QPushButton(ResetPassword)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout.addWidget(self.btn_reset)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(ResetPassword)
        QtCore.QMetaObject.connectSlotsByName(ResetPassword)

    def retranslateUi(self, ResetPassword):
        _translate = QtCore.QCoreApplication.translate
        ResetPassword.setWindowTitle(_translate("ResetPassword", "Reset Your Password"))
        self.lbl_message.setText(_translate("ResetPassword", "Please Enter Your New Password"))
        self.lbl_password1.setText(_translate("ResetPassword", "Password"))
        self.lbl_confirm_password.setText(_translate("ResetPassword", "Confirm Password"))
        self.btn_reset.setText(_translate("ResetPassword", "Reset"))
