# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings_tab(object):
    def setupUi(self, Settings_tab):
        Settings_tab.setObjectName("Settings_tab")
        Settings_tab.resize(622, 398)
        self.verticalLayout = QtWidgets.QVBoxLayout(Settings_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox_night_mode = QtWidgets.QHBoxLayout()
        self.hbox_night_mode.setObjectName("hbox_night_mode")
        self.lbl_night_mode = QtWidgets.QLabel(Settings_tab)
        self.lbl_night_mode.setObjectName("lbl_night_mode")
        self.hbox_night_mode.addWidget(self.lbl_night_mode)
        self.btn_nightmode = QtWidgets.QPushButton(Settings_tab)
        self.btn_nightmode.setText("")
        self.btn_nightmode.setObjectName("btn_nightmode")
        self.hbox_night_mode.addWidget(self.btn_nightmode)
        self.verticalLayout.addLayout(self.hbox_night_mode)
        self.line = QtWidgets.QFrame(Settings_tab)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.hbox_font = QtWidgets.QHBoxLayout()
        self.hbox_font.setObjectName("hbox_font")
        self.lbl_font = QtWidgets.QLabel(Settings_tab)
        self.lbl_font.setObjectName("lbl_font")
        self.hbox_font.addWidget(self.lbl_font)
        self.fcmbx_font = QtWidgets.QFontComboBox(Settings_tab)
        self.fcmbx_font.setObjectName("fcmbx_font")
        self.hbox_font.addWidget(self.fcmbx_font)
        self.verticalLayout.addLayout(self.hbox_font)
        self.line_2 = QtWidgets.QFrame(Settings_tab)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.hbox_color = QtWidgets.QHBoxLayout()
        self.hbox_color.setObjectName("hbox_color")
        self.lbl_color = QtWidgets.QLabel(Settings_tab)
        self.lbl_color.setObjectName("lbl_color")
        self.hbox_color.addWidget(self.lbl_color)
        self.btn_color = QtWidgets.QPushButton(Settings_tab)
        self.btn_color.setObjectName("btn_color")
        self.hbox_color.addWidget(self.btn_color)
        self.verticalLayout.addLayout(self.hbox_color)
        self.line_3 = QtWidgets.QFrame(Settings_tab)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.hbox_export = QtWidgets.QHBoxLayout()
        self.hbox_export.setObjectName("hbox_export")
        self.btn_export_apps = QtWidgets.QPushButton(Settings_tab)
        self.btn_export_apps.setObjectName("btn_export_apps")
        self.hbox_export.addWidget(self.btn_export_apps)
        self.btn_export_notes = QtWidgets.QPushButton(Settings_tab)
        self.btn_export_notes.setObjectName("btn_export_notes")
        self.hbox_export.addWidget(self.btn_export_notes)
        self.verticalLayout.addLayout(self.hbox_export)
        self.line_4 = QtWidgets.QFrame(Settings_tab)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.hbox_import = QtWidgets.QHBoxLayout()
        self.hbox_import.setObjectName("hbox_import")
        self.btn_import_apps = QtWidgets.QPushButton(Settings_tab)
        self.btn_import_apps.setObjectName("btn_import_apps")
        self.hbox_import.addWidget(self.btn_import_apps)
        self.btn_import_notes = QtWidgets.QPushButton(Settings_tab)
        self.btn_import_notes.setObjectName("btn_import_notes")
        self.hbox_import.addWidget(self.btn_import_notes)
        self.verticalLayout.addLayout(self.hbox_import)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_reset = QtWidgets.QPushButton(Settings_tab)
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout.addWidget(self.btn_reset)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Settings_tab)
        QtCore.QMetaObject.connectSlotsByName(Settings_tab)

    def retranslateUi(self, Settings_tab):
        _translate = QtCore.QCoreApplication.translate
        Settings_tab.setWindowTitle(_translate("Settings_tab", "Form"))
        self.lbl_night_mode.setText(_translate("Settings_tab", "Night Mode"))
        self.lbl_font.setText(_translate("Settings_tab", "Font"))
        self.lbl_color.setText(_translate("Settings_tab", "Color"))
        self.btn_color.setText(_translate("Settings_tab", "Choose Color"))
        self.btn_export_apps.setText(_translate("Settings_tab", "Export Apps"))
        self.btn_export_notes.setText(_translate("Settings_tab", "Export Notes"))
        self.btn_import_apps.setText(_translate("Settings_tab", "Import Apps"))
        self.btn_import_notes.setText(_translate("Settings_tab", "Import Notes"))
        self.btn_reset.setText(_translate("Settings_tab", "Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Settings_tab = QtWidgets.QWidget()
    ui = Ui_Settings_tab()
    ui.setupUi(Settings_tab)
    Settings_tab.show()
    sys.exit(app.exec_())
