# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/setup_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InitialSetup(object):
    def setupUi(self, InitialSetup):
        InitialSetup.setObjectName("InitialSetup")
        InitialSetup.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(InitialSetup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_setup = QtWidgets.QLabel(InitialSetup)
        self.lbl_setup.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_setup.setObjectName("lbl_setup")
        self.verticalLayout.addWidget(self.lbl_setup)
        self.stack_widget = QtWidgets.QStackedWidget(InitialSetup)
        self.stack_widget.setObjectName("stack_widget")
        self.verticalLayout.addWidget(self.stack_widget)
        self.btn_skip = QtWidgets.QPushButton(InitialSetup)
        self.btn_skip.setObjectName("btn_skip")
        self.verticalLayout.addWidget(self.btn_skip)

        self.retranslateUi(InitialSetup)
        self.stack_widget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(InitialSetup)

    def retranslateUi(self, InitialSetup):
        _translate = QtCore.QCoreApplication.translate
        InitialSetup.setWindowTitle(_translate("InitialSetup", "Initial Setup"))
        self.lbl_setup.setText(_translate("InitialSetup", "Initial Setup"))
        self.btn_skip.setText(_translate("InitialSetup", "Skip Setup"))
