# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/update_password.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UpdatePassword(object):
    def setupUi(self, UpdatePassword):
        UpdatePassword.setObjectName("UpdatePassword")
        UpdatePassword.resize(400, 190)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(UpdatePassword)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_password1 = QtWidgets.QLabel(UpdatePassword)
        self.lbl_password1.setObjectName("lbl_password1")
        self.verticalLayout.addWidget(self.lbl_password1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lne_password1 = QtWidgets.QLineEdit(UpdatePassword)
        self.lne_password1.setObjectName("lne_password1")
        self.horizontalLayout.addWidget(self.lne_password1)
        self.chk_show_password1 = QtWidgets.QCheckBox(UpdatePassword)
        self.chk_show_password1.setText("")
        self.chk_show_password1.setObjectName("chk_show_password1")
        self.horizontalLayout.addWidget(self.chk_show_password1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_password2 = QtWidgets.QLabel(UpdatePassword)
        self.lbl_password2.setObjectName("lbl_password2")
        self.verticalLayout_2.addWidget(self.lbl_password2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lne_password2 = QtWidgets.QLineEdit(UpdatePassword)
        self.lne_password2.setObjectName("lne_password2")
        self.horizontalLayout_2.addWidget(self.lne_password2)
        self.chk_show_password2 = QtWidgets.QCheckBox(UpdatePassword)
        self.chk_show_password2.setText("")
        self.chk_show_password2.setObjectName("chk_show_password2")
        self.horizontalLayout_2.addWidget(self.chk_show_password2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lbl_password_exp = QtWidgets.QLabel(UpdatePassword)
        self.lbl_password_exp.setObjectName("lbl_password_exp")
        self.verticalLayout_4.addWidget(self.lbl_password_exp)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dte_password_exp = QtWidgets.QDateEdit(UpdatePassword)
        self.dte_password_exp.setCalendarPopup(True)
        self.dte_password_exp.setObjectName("dte_password_exp")
        self.horizontalLayout_3.addWidget(self.dte_password_exp)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_3.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_password = QtWidgets.QPushButton(UpdatePassword)
        self.btn_password.setObjectName("btn_password")
        self.horizontalLayout_4.addWidget(self.btn_password)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)

        self.retranslateUi(UpdatePassword)
        QtCore.QMetaObject.connectSlotsByName(UpdatePassword)

    def retranslateUi(self, UpdatePassword):
        _translate = QtCore.QCoreApplication.translate
        UpdatePassword.setWindowTitle(_translate("UpdatePassword", "Update Password"))
        self.lbl_password1.setText(_translate("UpdatePassword", "New Password"))
        self.lbl_password2.setText(_translate("UpdatePassword", "Confirm Password"))
        self.lbl_password_exp.setText(_translate("UpdatePassword", "Password Expiration"))
        self.btn_password.setText(_translate("UpdatePassword", "Save"))
