# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vault_add_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSecret_window(object):
    def setupUi(self, AddSecret_window):
        AddSecret_window.setObjectName("AddSecret_window")
        AddSecret_window.resize(625, 234)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddSecret_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_name = QtWidgets.QLabel(AddSecret_window)
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout_2.addWidget(self.lbl_name)
        self.lnedt_name = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_name.setObjectName("lnedt_name")
        self.horizontalLayout_2.addWidget(self.lnedt_name)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(AddSecret_window)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(AddSecret_window)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.vbox_column_def = QtWidgets.QVBoxLayout()
        self.vbox_column_def.setObjectName("vbox_column_def")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lnedt_header1 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_header1.setObjectName("lnedt_header1")
        self.horizontalLayout_3.addWidget(self.lnedt_header1)
        self.lnedt_data1 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_data1.setObjectName("lnedt_data1")
        self.horizontalLayout_3.addWidget(self.lnedt_data1)
        self.vbox_column_def.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lnedt_header2 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_header2.setObjectName("lnedt_header2")
        self.horizontalLayout_4.addWidget(self.lnedt_header2)
        self.lnedt_data2 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_data2.setObjectName("lnedt_data2")
        self.horizontalLayout_4.addWidget(self.lnedt_data2)
        self.vbox_column_def.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lnedt_header3 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_header3.setObjectName("lnedt_header3")
        self.horizontalLayout_5.addWidget(self.lnedt_header3)
        self.lnedt_data3 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_data3.setObjectName("lnedt_data3")
        self.horizontalLayout_5.addWidget(self.lnedt_data3)
        self.vbox_column_def.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lnedt_header4 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_header4.setObjectName("lnedt_header4")
        self.horizontalLayout_6.addWidget(self.lnedt_header4)
        self.lnedt_data4 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_data4.setObjectName("lnedt_data4")
        self.horizontalLayout_6.addWidget(self.lnedt_data4)
        self.vbox_column_def.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lnedt_header5 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_header5.setObjectName("lnedt_header5")
        self.horizontalLayout_7.addWidget(self.lnedt_header5)
        self.lnedt_data5 = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_data5.setObjectName("lnedt_data5")
        self.horizontalLayout_7.addWidget(self.lnedt_data5)
        self.vbox_column_def.addLayout(self.horizontalLayout_7)
        self.verticalLayout.addLayout(self.vbox_column_def)
        self.hbox_data = QtWidgets.QHBoxLayout()
        self.hbox_data.setObjectName("hbox_data")
        self.btn_cancel = QtWidgets.QPushButton(AddSecret_window)
        self.btn_cancel.setObjectName("btn_cancel")
        self.hbox_data.addWidget(self.btn_cancel)
        self.btn_save = QtWidgets.QPushButton(AddSecret_window)
        self.btn_save.setObjectName("btn_save")
        self.hbox_data.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.hbox_data)

        self.retranslateUi(AddSecret_window)
        QtCore.QMetaObject.connectSlotsByName(AddSecret_window)

    def retranslateUi(self, AddSecret_window):
        _translate = QtCore.QCoreApplication.translate
        AddSecret_window.setWindowTitle(_translate("AddSecret_window", "Add Secret"))
        self.lbl_name.setText(_translate("AddSecret_window", "Display Name"))
        self.label.setText(_translate("AddSecret_window", "Add Headers"))
        self.label_2.setText(_translate("AddSecret_window", "Add Data"))
        self.btn_cancel.setText(_translate("AddSecret_window", "Cancel"))
        self.btn_save.setText(_translate("AddSecret_window", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddSecret_window = QtWidgets.QDialog()
    ui = Ui_AddSecret_window()
    ui.setupUi(AddSecret_window)
    AddSecret_window.show()
    sys.exit(app.exec_())
