# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vault_add_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddSecret_window(object):
    def setupUi(self, AddSecret_window):
        AddSecret_window.setObjectName("AddSecret_window")
        AddSecret_window.resize(625, 407)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddSecret_window)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox_column_spinbox = QtWidgets.QHBoxLayout()
        self.hbox_column_spinbox.setObjectName("hbox_column_spinbox")
        self.lbl_columns = QtWidgets.QLabel(AddSecret_window)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_columns.sizePolicy().hasHeightForWidth())
        self.lbl_columns.setSizePolicy(sizePolicy)
        self.lbl_columns.setObjectName("lbl_columns")
        self.hbox_column_spinbox.addWidget(self.lbl_columns)
        self.lnedt_columns = QtWidgets.QLineEdit(AddSecret_window)
        self.lnedt_columns.setObjectName("lnedt_columns")
        self.hbox_column_spinbox.addWidget(self.lnedt_columns)
        self.verticalLayout.addLayout(self.hbox_column_spinbox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(AddSecret_window)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(AddSecret_window)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.vbox_column_def = QtWidgets.QVBoxLayout()
        self.vbox_column_def.setObjectName("vbox_column_def")
        self.verticalLayout.addLayout(self.vbox_column_def)
        self.btn_add = QtWidgets.QPushButton(AddSecret_window)
        self.btn_add.setObjectName("btn_add")
        self.verticalLayout.addWidget(self.btn_add)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.hbox_data = QtWidgets.QHBoxLayout()
        self.hbox_data.setObjectName("hbox_data")
        self.btn_cancel = QtWidgets.QPushButton(AddSecret_window)
        self.btn_cancel.setObjectName("btn_cancel")
        self.hbox_data.addWidget(self.btn_cancel)
        self.btn_save = QtWidgets.QPushButton(AddSecret_window)
        self.btn_save.setObjectName("btn_save")
        self.hbox_data.addWidget(self.btn_save)
        self.verticalLayout.addLayout(self.hbox_data)

        self.retranslateUi(AddSecret_window)
        QtCore.QMetaObject.connectSlotsByName(AddSecret_window)

    def retranslateUi(self, AddSecret_window):
        _translate = QtCore.QCoreApplication.translate
        AddSecret_window.setWindowTitle(_translate("AddSecret_window", "Add Secret"))
        self.lbl_columns.setText(_translate("AddSecret_window", "Columns"))
        self.label.setText(_translate("AddSecret_window", "Field"))
        self.label_2.setText(_translate("AddSecret_window", "Data"))
        self.btn_add.setText(_translate("AddSecret_window", "Add"))
        self.btn_cancel.setText(_translate("AddSecret_window", "Cancel"))
        self.btn_save.setText(_translate("AddSecret_window", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddSecret_window = QtWidgets.QDialog()
    ui = Ui_AddSecret_window()
    ui.setupUi(AddSecret_window)
    AddSecret_window.show()
    sys.exit(app.exec_())
