# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'vault_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Vault_tab(object):
    def setupUi(self, Vault_tab):
        Vault_tab.setObjectName("Vault_tab")
        Vault_tab.resize(640, 382)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Vault_tab.sizePolicy().hasHeightForWidth())
        Vault_tab.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(Vault_tab)
        self.verticalLayout.setObjectName("verticalLayout")
        self.hbox_controls = QtWidgets.QHBoxLayout()
        self.hbox_controls.setObjectName("hbox_controls")
        self.chk_edit = QtWidgets.QCheckBox(Vault_tab)
        self.chk_edit.setObjectName("chk_edit")
        self.hbox_controls.addWidget(self.chk_edit)
        self.chk_view = QtWidgets.QCheckBox(Vault_tab)
        self.chk_view.setObjectName("chk_view")
        self.hbox_controls.addWidget(self.chk_view)
        self.chk_delete = QtWidgets.QCheckBox(Vault_tab)
        self.chk_delete.setObjectName("chk_delete")
        self.hbox_controls.addWidget(self.chk_delete)
        self.btn_add = QtWidgets.QPushButton(Vault_tab)
        self.btn_add.setObjectName("btn_add")
        self.hbox_controls.addWidget(self.btn_add)
        self.verticalLayout.addLayout(self.hbox_controls)
        self.gbox_secret = QtWidgets.QGridLayout()
        self.gbox_secret.setObjectName("gbox_secret")
        self.verticalLayout.addLayout(self.gbox_secret)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Vault_tab)
        QtCore.QMetaObject.connectSlotsByName(Vault_tab)

    def retranslateUi(self, Vault_tab):
        _translate = QtCore.QCoreApplication.translate
        Vault_tab.setWindowTitle(_translate("Vault_tab", "Form"))
        self.chk_edit.setText(_translate("Vault_tab", "Edit Secret"))
        self.chk_view.setText(_translate("Vault_tab", "View Secret"))
        self.chk_delete.setText(_translate("Vault_tab", "Delete Secret"))
        self.btn_add.setText(_translate("Vault_tab", "Add Secret"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Vault_tab = QtWidgets.QWidget()
    ui = Ui_Vault_tab()
    ui.setupUi(Vault_tab)
    Vault_tab.show()
    sys.exit(app.exec_())
