# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './xml/vault_type_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VaultTypeDialog(object):
    def setupUi(self, VaultTypeDialog):
        VaultTypeDialog.setObjectName("VaultTypeDialog")
        VaultTypeDialog.resize(282, 205)
        self.verticalLayout = QtWidgets.QVBoxLayout(VaultTypeDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_crypto = QtWidgets.QPushButton(VaultTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_crypto.sizePolicy().hasHeightForWidth())
        self.btn_crypto.setSizePolicy(sizePolicy)
        self.btn_crypto.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_crypto.setObjectName("btn_crypto")
        self.verticalLayout.addWidget(self.btn_crypto)
        self.btn_app = QtWidgets.QPushButton(VaultTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_app.sizePolicy().hasHeightForWidth())
        self.btn_app.setSizePolicy(sizePolicy)
        self.btn_app.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_app.setObjectName("btn_app")
        self.verticalLayout.addWidget(self.btn_app)
        self.btn_general = QtWidgets.QPushButton(VaultTypeDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_general.sizePolicy().hasHeightForWidth())
        self.btn_general.setSizePolicy(sizePolicy)
        self.btn_general.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_general.setObjectName("btn_general")
        self.verticalLayout.addWidget(self.btn_general)

        self.retranslateUi(VaultTypeDialog)
        QtCore.QMetaObject.connectSlotsByName(VaultTypeDialog)

    def retranslateUi(self, VaultTypeDialog):
        _translate = QtCore.QCoreApplication.translate
        VaultTypeDialog.setWindowTitle(_translate("VaultTypeDialog", "Choose Your Vault Type"))
        self.btn_crypto.setText(_translate("VaultTypeDialog", "Crypto Vault"))
        self.btn_app.setText(_translate("VaultTypeDialog", "App Vault"))
        self.btn_general.setText(_translate("VaultTypeDialog", "General Vault"))
